$schema: "http://json-schema.org/draft-07/schema#"
type: object
properties:
  id:
    type: string
  practice:
    type: object
    properties:
      title:
        type: string
      creator:
        type: string
      format:
        type: object
        additionalProperties:
          type: string
      options:
        type: object
        properties:
          category:
            type: string
          looping:
            type: array
            items:
              type: string
        additionalProperties: false
      compression:
        type: string
      order:
        type: array
        items:
          type: string
      size:
        type: object
        properties:
          minimum:
            type: integer
        additionalProperties: false
    required:
      - title
      - creator
      - format
      - options
  references:
    type: array
    items:
      type: object
      properties:
        type:
          type: string
        value:
          type: string
      required:
        - type
        - value
    additionalItems: false
required:
  - id
  - practice
